### ISSUE TITLE
Thanks! Awesome script!, solve my problem!

### ISSUE THREAD

**Issue by 1c7** [Zren/ResizeYoutubePlayerToWindowSize#22]
maybe you can use other name like "super thator mode" or something.
it is hard to search.

wow. 754 line of code. I didn't except that much.
Thanks for your time!

**Comment by Zren** [comment]
Thanks for using it! More users = more incentive to not be lazy.

Yeah, there's a lot of bloat. I wrote the first version in 2012 when ES6 wasn't common. I could probably remove the `jQuery.addClass()` since `element.classList.add()` is not supported. There's a lot of lines that would be much smaller if written in plain CSS, but meh. Fixing the HTML5 seekbar uses so many lines though. Properly fixing that thing is such a pain. Half of the code is just debugging for when it breaks.
