### ISSUE TITLE
130 theater mode not working since 129

### ISSUE THREAD

**Issue by Krakkan83** [Zren/ResizeYoutubePlayerToWindowSize#75]
129: Fix toggling theater mode as YouTube moved the button into the settings cog menu (Issue #66)

On my Youtube the theater button is **not** in the cog menu so theater mode never starts, resulting in a short video bar that doesn't stretch all the way under the video, stopping less then half way.

Hope it's understandable what i mean and that it can be fixed.

**Comment by Zren** [comment]
I can reproduce in Firefox on Win11 and Linux.

https://github.com/Zren/ResizeYoutubePlayerToWindowSize/blob/4cafdad632aa4356c384b156776231516c507af0/153699.user.js#L214

It's detecting `var watchElement` properly, it's assigned `ytd-watch-flexy`. However the issue is that `ytd-watch-flexy` has child elements in the DOM, but `watchElement.children` and `watchElement.childNodes` is empty arrays.

This means that 

```js
var sizeButton = watchElement.querySelector('button.ytp-size-button')
```

will return `null` for some reason. However if I use 

```js
var sizeButton = document.querySelector('ytd-watch-flexy button.ytp-size-button')
```

the button is properly found. This is probably because of YT/Google's "fake DOM" code or something.

I should be able to use the following to make it able to detect `ytd-watch` and `ytd-watch-flexy`.

```js
var sizeButton = document.querySelector(watchElement.tagName + ' button.ytp-size-button')
```
