### ISSUE TITLE
Question: How often does Youtube break this script?

### ISSUE THREAD

**Issue by elundmark** [Zren/ResizeYoutubePlayerToWindowSize#9]
I'm curious to know how often Youtube changes their code (on average), and forces you to update the code..? And it it's _often_, what is the most common edit they make?
Pure curiosity... :-)
P.S. This is my No.1 userscript installation (I'm really surprised this feature hasn't become mainstream years ago btw), and the one I recommend most to people ;-) Many thanks for the grunt work :-)

**Comment by Zren** [comment]
Their code is minified, which obfuscates any private variables. Whenever they push a new version, the obfuscated variables change. I just pushed a new version that ignores what the variable names are and looks at the values instead. I origionally planned to manually update the variable names but I guess Youtube pushed like 5 billion versions this last week when they mad the HTML5 player default for all browsers. I used to be able to get away with using those variables for a month or so.

**Comment by elundmark** [comment]
Intresting... and I'm guessing there's no way to make the video resize and moved to the top without the internal variables, using only css and pure javascript resizing? I was about to try writing something like that for myself, just for the challange...
Thanks for the info!

**Comment by Zren** [comment]
You used to be able to do it with just css. You can easily set the width of some things to 100% width, but the progressbar and the annotations depend on overlaying the video and deal with absolute positioned values calculated with javascript because they move. Instead of using percentages, theyre calculated in pixels. And the value used to calculate the size of the player uses a hardcoded size in the default conditions rather than looking at the width of the element.
